<?php use function Blog\View\display;?>
<?php $username= $_SESSION['username'] ?? $_GET['username'] ?? 'Guest';?>
<!doctype html>
<html>
<head>
    <title>Superglobals Blog</title>
    <link rel="icon" type="image/png"  href="img/logo_mini.png">
    <link href="css/main.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="header">
        <a href="index.php"><img src="img/logo.png" alt="logo" /></a>
  <h1>Welcome to the World of Superglobal Blogging</h1>
</div>
    <?= display('links');?>
   
    
    <?php if ($username == 'Guest'): ?>
 
	<?=  "Please login/register to view and post articles"; ?>
 
    <?php else: ?>

    <?= "You are logged in as: $username" ?>

    <?php endif;  ?>

    <?= display('searchform');?>
    <?= display('categories');?>
  
  
