<?php use function Blog\View\display;?>
<!doctype html>
<html>
<head>
    <title>Superglobals Blog</title>
    <!--<link rel="icon" type="image/png"  href="img/mini_logo.png">-->
    <link href="css/main.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="header">
  <img src="img/logo.png" alt="logo" />
  <h1>Welcome to the World of Superglobal Blogging</h1>
</div>
    <?= display('links');?>
  
  
  
