<div class="content post">
    
    <?=  "<a href=article.php?id=" . $article['id'] . ">" ?> 
        <h1 class="post-title"><?= $article['title'] ?></h1></a>    
    <div class="post-date">

            <time><?= date($article['creationdate']); ?></title>
            <?= $article['username']; ?>
    </div>
	
        
      <?php if(file_exists("uploads/articles/{$article['id']}.jpg")): ?>
		<img src="uploads/articles/<?=$article['id'];?>.jpg" width="150" />
	<?php endif; ?>

       <?= $article['body']; ?>         
                
</div>

