<div>
    <a href="index.php">Home</a>    
  
    <?php if (isset($_SESSION['username'])) {
         echo '<a href="logout.php">Logout</a>';
    } 
    else {
        echo '<a href="login.php">Login/Register</a>';
    }
    ?> 
    
    <!--<a href="article.php">Article</a>-->
    <a href="user.php">Profile Page</a>
    <a href="archive.php">Archive</a>
    <a href="NewArticle.php">Create New Article</a>

    
    <?php if (isset($_SESSION['user']['role']) && $_SESSION['user']['role']==2) {
    echo '<a href="admin.php">Admin</a>';}
    ?> 
</div>
