<div>
    <a href="index.php">Home</a>    
  
    <?php if (isset($_SESSION['username'])): ?>
    
         <?= '<a href="logout.php">Logout</a>'; ?>
     
    <?php else: ?>
    
        <?= '<a href="login.php">Login/Register</a>'; ?>

    <?php endif; ?> 
    
    <a href="user.php">Profile Page</a>
    <a href="archive.php">Archive</a>
    <a href="NewArticle.php">Create New Article</a>

    
    <?php if (isset($_SESSION['user']['role']) && $_SESSION['user']['role']==2): ?>
        
        <?=  '<a href="admin.php">Admin</a>'; ?>
    
    <?php endif; ?>

   
</div>
