<span id="LoginForm">
    <h1>Please log in with your username and password</h1>
    <form name="login" action="login.php" method="post">
        <p>
      <label for="username">Username: </label>
      <input name="username" type="text"  autofocus required placeholder="Enter your username"/>
      </p>

      <p>
      <label for="password">Password: </label>
      <input name="password" type="password" required placeholder="Enter your password"/>
      </p>

      <button type="submit" id="login" name="login" value="login">Login</button>
    </form>
    
    
</span>