<div id="LoginForm">
    <h1>Existing User Login</h1>
    <form action="login.php" method="post">
      <div>
      <label for="username">Username: </label>
      <input name="username" type="text" required/>
      </div>

      <div>
      <label for="password">Password: </label>
      <input name="password" type="password" required/>
      </div>

      <button type="submit" value="login">Login</button>
    </form>
</div>