<!--Post article form-->

        <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>"
            method="post"      
            enctype="multipart/form-data" >
            
            <input type="hidden" 
            accept=""name="MAX_FILE_SIZE" 
            accesskey=""value="10000000" />
            
           <br>Select a Category for your article
            
            <select name="category">
                
            <?php foreach (CATEGORIES as $category) {
                    echo "<option value=" . array_search($category,CATEGORIES) . ">" . $category . "</option>";} ?>
            </select>
            
            <br
            
            Add a title for your article:<br>
            <input type="text" name="title">
             <br>
            Type your article here:<br>
            <textarea name="body" rows="50" cols="100"></textarea>
            
            <br>Choose and image for the end of your article<br>
            <input type="file" name="image_end" />
            
            <input type="submit" value="send" />
            
            <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
        </form>