<div id="CommentForm">
    <h2>Add a comment</h2>
    <form name="comment" action="article.php" method="post">
      <div>
      <label for="Comment">Comment: </label>
      <input name="comment" type="text"  autofocus required placeholder="Enter your comments here..."/>
      </div>
      <button type="submit" id="comment" name="comment" value="comment">Submit comment</button>
    </form>
   
</div>