<div id="RegisterForm"></div>
    <h1>Not yet registered? Enter your details here:</h1>
      <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>"
            method="post"      
            enctype="multipart/form-data" >
            
            <input type="hidden" 
            accept=""name="MAX_FILE_SIZE" 
            accesskey=""value="10000000" />
            
      <div>
      <label for="firstname">First name: </label>
      <input name="firstname" type="text" required pattern=".{2,}" placeholder="Enter your first name"/>
      </div>

      <div>
      <label for="lastname">Last name: </label>
      <input name="lastname" type="text" required pattern=".{2,}"  placeholder="Enter your last name"/>
      </div>

        <div>
      <label for="username">Username: </label>
      <input name="username" type="text" required pattern=".{5,}"  placeholder="Choose a username (min 5 characters)"/>
      </div>

      <div>
      <label for="email">Email: </label>
      <input name="email" type="text" required  placeholder="Enter your email address"/>
      </div>
        
      <div>
      <br>
            A short bio: <br>
       <textarea name="bio" rows="5" cols="30"></textarea>
       
      </div>
            <br>Upload a profile pic: </br>
            <input type="file" name="profile_pic" />
      <div>
          
      <label for="password">Password: </label>
      <input name="password" type="password" required  placeholder="Enter a password (at least 6 characters with an uppercase letter and a number"
             pattern="^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).*$"/>
      </div>

      <div>
      <label for="verifypassword">Verify Password: </label>
      <input name="verifypassword" type="password"  placeholder="Enter your password again"/>
      </div>

       
        
      <button type="submit" id="register" name="register" value="register">Register</button>
    </form>
</div>