
<div>
  
        <h2>Username: <?= $users['username']; ?></h2>
	<p>User ID: <?= $users['id']; ?></p>
	<p>Email: <?= $users['email']; ?></p>
        <p>Full name : <?= $users['firstname'] . " " . $users['lastname']; 
            ?></p>
       
        <p>
             <?php if (isset($_SESSION['user']['role']) && $_SESSION['user']['role']==2): ?>
        
                    <?=   '<a href="deleteuser.php?id=' .  $users['id'] . '">Delete</a>'; ?>
    
            <?php endif; ?> 
        </p>
   
                     
            
</div>
