
<div>
  
        <h2>Username: <?= $users['username']; ?></h2>
	<p>User ID: <?= $users['id']; ?></p>
	<p>Email: <?= $users['email']; ?></p>
        <p>Full name: <?= $users['firstname'] . " " . $users['lastname']; 
            ?></p>
       
        <p>
             <?php if (isset($_SESSION['user']['role']) && $_SESSION['user']['role']==2): ?>
        
                    <?=   '<a href="delete.php?user_id=' .  $users['id'] . '">Delete</a>'; ?>
    
            <?php endif; ?> 
        </p>

        <p>
           <?php if(file_exists("uploads/profiles/{$users['id']}.jpg")): ?>
		<img src="uploads/profiles/<?=$users['id'];?>.jpg" width="150" />
            <?php endif; ?>
                
        <p>Bio: <?= $users['bio']; ?></p>
                    
            
</div>
